package com.prodapt.app.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.prodapt.app.model.dto.ApiResponse;
import com.prodapt.app.model.prodapt.Users;
import com.prodapt.app.service.UserService;

/**
 * @author arunkumar.a
 *
 */
@RestController
public class UsersController {
	
	@Autowired
	UserService userService;
	
	@GetMapping("/v1/getAllUsers")
	public List<Users> getAllUsers() {
		return userService.getAllUsersFromRepo();
	}
	
	@GetMapping("/v1/getUser/{id}")
	public ResponseEntity<?> getUsersId(
			@PathVariable("id") Integer id) 
	{
		return new ResponseEntity<>(userService.getUsersByIdFromRepo(id),HttpStatus.OK);
	}
	
	
	/**
	 * @author arunkumar.a
	 *
	 * Using PUT method since the id of the user is not generated by server or database and it is passed by client application
	 */
	@PutMapping("/v1/SaveUsers")
	public ResponseEntity<?> saveUsers(
			@RequestBody List<Users> users) 
	{
		ResponseEntity<ApiResponse> apiResp = userService.saveUsersInRepo(users);
		
		return apiResp;
		
	}
	
	@DeleteMapping("/v1/deleteUser/{id}")
	public ResponseEntity<?> deleteUserById(
			@PathVariable("id") Integer id) 
	{		
		ResponseEntity<ApiResponse> apiResp = userService.deleteUserByIdFromRepo(id);
		
		return apiResp;
	}
	

}
